import type { HardwareProfile } from "../hardware/types.js";
import { catalog, lastVerified, tiers } from "./catalog.js";
import type { RecommendationReport } from "./recommend.js";

function gb(n: number): string {
  return `${Math.round(n * 10) / 10} GB`;
}

/**
 * Render `core/models.md` for a specific machine. Pure: string in, string out.
 */
export function renderModelsDoc(
  hw: HardwareProfile,
  report: RecommendationReport,
  chosen: string,
): string {
  const top = report.list[0];
  const tierRows = tiers
    .map((t) => {
      const mark = t === report.tier ? " ← this machine" : "";
      const alts = t.alsoOffer.map((a) => `\`${a}\``).join(", ");
      return `| ${t.label}${mark} | \`${t.recommended}\` | ${alts} | ${t.reason} |`;
    })
    .join("\n");

  const catalogRows = catalog
    .map(
      (m) =>
        `| \`${m.tag}\` | ${m.params} | ~${m.sizeGB} GB | ${m.contextK}K | ${m.notes}${m.appleOnly ? " (Apple Silicon only)" : ""} |`,
    )
    .join("\n");

  const adjustments =
    report.adjustments.length > 0
      ? `\n**Adjustments applied on this machine:**\n${report.adjustments.map((a) => `- ${a}`).join("\n")}\n`
      : "";

  const gpu =
    hw.gpu.kind === "apple"
      ? "Apple Silicon (unified memory)"
      : hw.gpu.kind === "none"
        ? "none detected"
        : `${hw.gpu.model}${hw.gpu.vramGB ? ` (${gb(hw.gpu.vramGB)} VRAM)` : ""}`;

  return `# Choosing the executor model

Generated by \`local-executor\` for this machine on ${new Date().toISOString().slice(0, 10)}. Catalog last verified against ollama.com on ${lastVerified}.

## This machine

| | |
|---|---|
| OS / arch | ${hw.platform} / ${hw.arch} |
| CPU | ${hw.cpuModel} (${hw.physicalCores} physical / ${hw.logicalCores} logical cores) |
| RAM | ${gb(hw.totalRamGB)} total, ${gb(hw.freeRamGB)} free at install time |
| GPU | ${gpu} |
| Effective memory for models | **${gb(report.effectiveMemory.gb)}** (${report.effectiveMemory.rule}) |
| Free disk near the model store | ${gb(hw.freeDiskGB)} (${hw.modelsDir}) |
| Configured executor | **\`${chosen}\`** |
| Top recommendation | \`${top?.tag ?? "n/a"}\` — ${top?.reason ?? ""} |
${adjustments}
## The rule

The model file plus its context cache must fit in memory alongside the OS, the agent, and an editor. On Apple Silicon roughly 70% of unified RAM is usable for the model; on a PC with a discrete NVIDIA/AMD GPU, count VRAM; on CPU-only x64, count about half of RAM. A model that doesn't fit swaps to disk and drops to 1–2 tokens/sec — worse than useless.

Mixture-of-Experts models (e.g. Gemma 4 26B, "4B active") are fast to compute but still need the **whole** model in memory. Active-parameter count is not memory footprint. That is why a 26B MoE does not fit on a 16 GB Mac even though only 4B parameters run per token.

## Tiers

| Effective memory | Recommended | Alternatives | Notes |
|---|---|---|---|
${tierRows}

Below 4 physical cores on a CPU-only machine, step down until the recommended model gets smaller. If the recommended model needs more than the free disk × 1.5, step down and free space.

## Catalog (sizes approximate)

| Tag | Parameters | Download | Context | Notes |
|---|---|---|---|---|
${catalogRows}

Verify tag names on ollama.com before pulling something not in this list — tags change between releases.

## Cold start

The first call after the model unloads takes 10–30 s while it loads. The runtime passes \`keep_alive\` (default 30m, in \`config.json\`) so the model stays resident between packets. Set \`OLLAMA_KEEP_ALIVE=-1\` in the environment to keep it loaded permanently while working.

## Context window

\`num_ctx\` in \`config.json\` is 16384. Larger contexts cost memory (the KV cache grows linearly). If the model starts swapping, drop \`num_ctx\` to 8192 before stepping down a model size — most packets fit in 8k.

## Changing the model

Run \`lex switch <tag>\`. It pulls the tag if needed and updates every installed \`config.json\`. Editing \`config.json\` by hand and running \`ollama pull <tag>\` also works.
`;
}
